name: build_and_deploy (manual)

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_CACHE: ${{ runner.temp }}/npm-cache
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean any stale npm tmp (best-effort)
        run: rm -rf ~/.npm/_cacache/tmp || true

      - name: Install dependencies
        run: npm ci --no-audit --no-fund --cache $NPM_CONFIG_CACHE --prefer-offline

      - name: Build
        run: npm run build

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy to Firebase Hosting
        if: github.ref == 'refs/heads/main'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"


