name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main   # change if you deploy from another branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > "${HOME}/firebaseServiceAccount.json"
          export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/firebaseServiceAccount.json"
          firebase deploy --only hosting --project ippon-whisper-app
